### ISSUE TITLE
It gives a window permission error. I've tried to fix the issue but failed to do so. Please let us know about the corrected code. Looking forward to run the app.

### ISSUE THREAD

**Issue by soumithganji** [Mirrorhanyu/AssistiveTouch#2]

**Comment by mirrorhanyu** [comment]
Hi soumithganjim!

Thanks for your interest in this application, but it is no longer maintained, and the code of this implementation is not the best practice to fit the latest android development. my suggestion would be implement this kind of feature by your own new way.
